usr/lib/*/*.so
usr/lib/*/*.so.*
etc/mixer_paths_qcm6490_idp.xml /etc/
etc/mixer_paths_qcs6490_rb3gen2.xml /etc/
etc/mixer_paths_qcs6490_rb3gen2_ia.xml /etc/
etc/mixer_paths_qcs6490_rb3gen2_video.xml /etc/
etc/mixer_paths_qcs6490_rb3gen2_vision.xml /etc/
etc/mixer_paths_qcs8275_rb4.xml /etc/
etc/mixer_paths_qcs8300_ridesx.xml /etc/
etc/mixer_paths_qcs9075_rb8.xml /etc/
etc/mixer_paths_qcs9100_ridesx.xml /etc/
etc/mixer_paths_iq8_8275_evk.xml /etc/
etc/resourcemanager_qcm6490_idp.xml /etc/
etc/resourcemanager_qcs6490_rb3gen2.xml /etc/
etc/resourcemanager_qcs6490_rb3gen2_ia.xml /etc/
etc/resourcemanager_qcs6490_rb3gen2_video.xml /etc/
etc/resourcemanager_qcs6490_rb3gen2_vision.xml /etc/
etc/resourcemanager_qcs8275_rb4.xml /etc/
etc/resourcemanager_qcs8300_ridesx.xml /etc/
etc/resourcemanager_qcs9075_rb8.xml /etc/
etc/resourcemanager_qcs9100_ridesx.xml /etc/
etc/resourcemanager_iq8_8275_evk.xml /etc/
etc/usecaseKvManager.xml /etc/
