#ifndef SECBOOT_TOOL_CHIPSET_H
#define SECBOOT_TOOL_CHIPSET_H

/**
@file secboot_tool_chipset.h
*/

/*===========================================================================
   Copyright (c) 2022-2023 by QUALCOMM Technology, Inc.  All Rights Reserved.
===========================================================================*/

/*----------------------------------------------------------------------------
 * Include Files
 * -------------------------------------------------------------------------*/
#include "sail_sec_hwio.h"
#include "HALhwio.h"

// This gives the valid QFPROM regions which can be compared using secboot tool  
static uint32_t secboot_tool_feat_secelf_valid_regions[] =
{
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_READ_PERMISSIONS_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_WRITE_PERMISSIONS_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_FEC_ENABLES_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_OEM_CONFIG_ROW0_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_OEM_CONFIG_ROW1_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_OEM_CONFIG_ROW2_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_PK_HASH_0_ROW0_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_PK_HASH_0_ROW1_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_PK_HASH_0_ROW2_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_PK_HASH_0_ROW3_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_PK_HASH_0_ROW4_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_PK_HASH_0_ROW5_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_OEM_IMAGE_ENCRYPTION_KEY_ROW0_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_OEM_IMAGE_ENCRYPTION_KEY_ROW1_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_OEM_IMAGE_ENCRYPTION_KEY_ROW2_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_OEM_SECURE_BOOT_ROW0_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_OEM_SECURE_BOOT_ROW1_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_SEC_KEY_DERIVATION_KEY_ROW0_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_SEC_KEY_DERIVATION_KEY_ROW1_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_SEC_KEY_DERIVATION_KEY_ROW2_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_SEC_KEY_DERIVATION_KEY_ROW3_LSB_ADDR,
  HWIO_SAILSS_SECURITY_CONTROL_QFPROM_RAW_SEC_KEY_DERIVATION_KEY_ROW4_LSB_ADDR,
};

static uint32_t secboot_tool_feat_secelf_valid_regions_size = sizeof(secboot_tool_feat_secelf_valid_regions)/sizeof(secboot_tool_feat_secelf_valid_regions[0]);

#endif /* SECBOOT_TOOL_CHIPSET_H */
