#ifndef SAIL_ASILD_ISO_HWIO_H
#define SAIL_ASILD_ISO_HWIO_H
/*
===========================================================================
*/
/**
    @file sail_asild_iso_hwio.h
    @brief Auto-generated HWIO interface include file.

    Reference chip release:
        SA8775P (LeMansAU) r2 [lemansau_2.0_p3q3r42_MTO]
 
    This file contains HWIO register definitions for the following modules:
        SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK

    'Include' filters applied: SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW[SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK] SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW[SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK] SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW[SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK] 

    Generation parameters: 
    { 'filename': 'sail_asild_iso_hwio.h',
      'header': '#include "msmhwiobase.h"',
      'integer-qualifiers': True,
      'module-filter-include': { 'SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK': [ 'SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW',
                                                                                     'SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW',
                                                                                     'SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW']},
      'modules': ['SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK'],
      'output-attrs': True,
      'output-fvals': True,
      'output-offsets': True}

    Attribute definitions for the HWIO_*_ATTR macros are as follows:
        0x0: Command register
        0x1: Read-Only
        0x2: Write-Only
        0x3: Read/Write
*/
/*
    ===========================================================================

    Copyright (c) 2023 Qualcomm Technologies, Inc.
    All Rights Reserved.
    Confidential and Proprietary - Qualcomm Technologies, Inc.

    Export of this technology or software is regulated by the U.S. Government.
    Diversion contrary to U.S. law prohibited.

    All ideas, data and information contained in or disclosed by
    this document are confidential and proprietary information of
    Qualcomm Technologies, Inc. and all rights therein are expressly reserved.
    By accepting this material the recipient agrees that this material
    and the information contained therein are held in confidence and in
    trust and will not be used, copied, reproduced in whole or in part,
    nor its contents revealed in any manner to others without the express
    written permission of Qualcomm Technologies, Inc.

    ===========================================================================

    $Header: $
    $DateTime: $
    $Author: $

    ===========================================================================
*/

#include "msmhwiobase.h"

/*----------------------------------------------------------------------------
 * MODULE: SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK
 *--------------------------------------------------------------------------*/

#define SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE                                                      (SAILSS_ASIL_D_SAIL_ASIL_D_NOC_WRAPPER_BASE      + 0x00040000UL)
#define SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE_SIZE                                                 0x6a00U
#define SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE_USED                                                 0x6900U
#define SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE_OFFS                                                 0x00040000UL

#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_ADDR                        (SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE      + 0x4008U)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_OFFS                        (SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE_OFFS + 0x4008U)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_RMSK                               0x1U
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_ATTR                                     0x3
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_IN                    \
                in_dword(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_ADDR)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_INM(m)            \
                in_dword_masked(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_ADDR, m)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_OUT(v)            \
                out_dword(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_ADDR,v)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_ADDR,m,v,HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_IN)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_GLBEN_BMSK                         0x1U
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_MAINCTL_LOW_GLBEN_SHFT                           0U

#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_ADDR                        (SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE      + 0x4040U)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_OFFS                        (SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE_OFFS + 0x4040U)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_RMSK                             0x11fU
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_ATTR                                     0x3
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_IN                    \
                in_dword(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_ADDR)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_INM(m)            \
                in_dword_masked(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_ADDR, m)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_OUT(v)            \
                out_dword(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_ADDR,v)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_ADDR,m,v,HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_IN)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_ENABLE_BMSK                      0x100U
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_ENABLE_SHFT                          8U
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_RATIO_BMSK                        0x1fU
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL0_LOW_RATIO_SHFT                           0U

#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_ADDR                        (SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE      + 0x4048U)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_OFFS                        (SAILSS_ASIL_D_ISOLATIONNOC_DEC_SERVICE_NETWORK_REG_BASE_OFFS + 0x4048U)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_RMSK                             0x11fU
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_ATTR                                     0x3
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_IN                    \
                in_dword(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_ADDR)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_INM(m)            \
                in_dword_masked(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_ADDR, m)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_OUT(v)            \
                out_dword(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_ADDR,v)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_ADDR,m,v,HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_IN)
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_ENABLE_BMSK                      0x100U
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_ENABLE_SHFT                          8U
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_RATIO_BMSK                        0x1fU
#define HWIO_SAILSS_ASIL_D_ISOLATIONNOC_SAIL_ISOLATION_TIMEOUT_REFGEN_REFGEN_REFCTL1_LOW_RATIO_SHFT                           0U


#endif /* SAIL_ASILD_ISO_HWIO_H */
