#ifndef __G_SAIL_TO_MD_GPU_GMU_AO_HWIO_H__
#define __G_SAIL_TO_MD_GPU_GMU_AO_HWIO_H__
/*
===========================================================================
*/
/**
    @file g_SAIL_TO_MD_GPU_GMU_AO_HWIO.h
    @brief Auto-generated HWIO interface include file.

    Reference chip release:
        SA8775P (LeMansAU) [lemansau_v1.0_p3q2r72_BTO]
 
    This file contains HWIO register definitions for the following modules:
        SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0


    Generation parameters: 
    { 'filename': 'g_SAIL_TO_MD_GPU_GMU_AO_HWIO.h',
      'integer-qualifiers': True,
      'modules': ['SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0'],
      'output-fvals': True,
      'output-offsets': True}
*/
/*
    ===========================================================================

    Copyright (c) 2022 Qualcomm Technologies, Inc.
    All Rights Reserved.
    Confidential and Proprietary - Qualcomm Technologies, Inc.

    Export of this technology or software is regulated by the U.S. Government.
    Diversion contrary to U.S. law prohibited.

    All ideas, data and information contained in or disclosed by
    this document are confidential and proprietary information of
    Qualcomm Technologies, Inc. and all rights therein are expressly reserved.
    By accepting this material the recipient agrees that this material
    and the information contained therein are held in confidence and in
    trust and will not be used, copied, reproduced in whole or in part,
    nor its contents revealed in any manner to others without the express
    written permission of Qualcomm Technologies, Inc.

    ===========================================================================

    $Header: $
    $DateTime: $
    $Author: $

    ===========================================================================
*/

/*----------------------------------------------------------------------------
 * MODULE: SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0
 *--------------------------------------------------------------------------*/

#define SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE                                                (SAIL_TO_MD_SAILS_TO_MD_CONFIG_BASE      + 0x03d8ec00ul)
#define SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_SIZE                                           0xc0u
#define SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_USED                                           0xa0u
#define SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS                                           0x03d8ec00ul

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_IBITS_ADDR                                     (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x0u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_IBITS_OFFS                                     (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x0u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_IBITS_RMSK                                     0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_IBITS_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_IBITS_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_IBITS_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_IBITS_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_IBITS_INTRSTATUS_BMSK                          0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_IBITS_INTRSTATUS_SHFT                                   0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_ADDR                                        (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x4u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_OFFS                                        (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x4u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_RMSK                                        0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_INTREN_BMSK                                 0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_EN_INTREN_SHFT                                          0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_CLR_ADDR                                       (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x8u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_CLR_OFFS                                       (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x8u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_CLR_RMSK                                       0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_CLR_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_CLR_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_CLR_INTRCLR_BMSK                               0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_DOORBELL_CLR_INTRCLR_SHFT                                        0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_ADDR                                        (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0xcu)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_OFFS                                        (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0xcu)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_RMSK                                               0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_DBDWAKEUPEN_BMSK                                   0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AO_INTERRUPT_EN_DBDWAKEUPEN_SHFT                                     1u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_ADDR                                     (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x10u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_OFFS                                     (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x10u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_RMSK                                           0x19u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_DBDWAKEUPCLR_BMSK                              0x10u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_DBDWAKEUPCLR_SHFT                                 4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_FENCEERRCLR_BMSK                                0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_FENCEERRCLR_SHFT                                  3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_WDOGBITECLR_BMSK                                0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_CLR_WDOGBITECLR_SHFT                                  0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_ADDR                                  (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x14u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_OFFS                                  (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x14u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_RMSK                                        0x3fu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_RSCCERROR_BMSK                              0x20u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_RSCCERROR_SHFT                                 5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_DBDWAKEUP_BMSK                              0x10u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_DBDWAKEUP_SHFT                                 4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_FENCEERR_BMSK                                0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_FENCEERR_SHFT                                  3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_VDROOP_BMSK                                  0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_VDROOP_SHFT                                    2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_RSCCCOMP_BMSK                                0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_RSCCCOMP_SHFT                                  1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_WDOGBITE_BMSK                                0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_STATUS_WDOGBITE_SHFT                                  0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_ADDR                                    (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x18u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_OFFS                                    (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x18u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_RMSK                                          0x3fu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_RSCCERRORMASK_BMSK                            0x20u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_RSCCERRORMASK_SHFT                               5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_DBDWAKEUPMASK_BMSK                            0x10u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_DBDWAKEUPMASK_SHFT                               4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_FENCEERRMASK_BMSK                              0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_FENCEERRMASK_SHFT                                3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_VDROOPMASK_BMSK                                0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_VDROOPMASK_SHFT                                  2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_RSCCCOMPMASK_BMSK                              0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_RSCCCOMPMASK_SHFT                                1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_WDOGBITEMASK_BMSK                              0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_HOST_INTERRUPT_MASK_WDOGBITEMASK_SHFT                                0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_ADDR                                   (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x1cu)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_OFFS                                   (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x1cu)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_RMSK                                          0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_BRINGUPREQ_BMSK                               0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_BRINGUPREQ_SHFT                                 1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_SHUTDOWNREQ_BMSK                              0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_REQ_SHUTDOWNREQ_SHFT                                0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_ADDR                                   (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x20u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_OFFS                                   (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x20u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_RMSK                                          0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_BRINGUPACK_BMSK                               0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_BRINGUPACK_SHFT                                 1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_SHUTDOWNACK_BMSK                              0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_RSCC_CONTROL_ACK_SHUTDOWNACK_SHFT                                0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_ADDR                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x24u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_OFFS                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x24u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_RMSK                                         0x70777ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLLLMMODE_BMSK                          0x70000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLLLMMODE_SHFT                               16u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLLLMMODE_GMU_AO_0_ENABLE_CLK_CORE_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLLLMMODE_GMU_AO_0_DISABLE_CLK_CORE_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLLLMMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT0_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLLLMMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT1_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLLLMMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT2_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLLLMMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT0_2_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCSRMODE_BMSK                            0x700u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCSRMODE_SHFT                                8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCSRMODE_GMU_AO_0_ENABLE_CLK_CORE_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCSRMODE_GMU_AO_0_DISABLE_CLK_CORE_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCSRMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT0_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCSRMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT1_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCSRMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT2_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCSRMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT0_2_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3BUSMODE_BMSK                          0x70u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3BUSMODE_SHFT                             4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3BUSMODE_GMU_AO_0_ENABLE_CLK_CORE_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3BUSMODE_GMU_AO_0_DISABLE_CLK_CORE_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3BUSMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT0_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3BUSMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT1_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3BUSMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT2_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3BUSMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT0_2_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3COREMODE_BMSK                          0x7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3COREMODE_SHFT                            0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3COREMODE_GMU_AO_0_ENABLE_CLK_CORE_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3COREMODE_GMU_AO_0_DISABLE_CLK_CORE_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3COREMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT0_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3COREMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT1_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3COREMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT2_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_MODE_CNTL_CGCCNTLCM3COREMODE_GMU_AO_0_USE_CORE_CGCTRL_KEEP_ON_BIT0_2_FVAL        0x5u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_ADDR                                     (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x28u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_OFFS                                     (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x28u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_RMSK                                        0x70777ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_BMSK                        0x70000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_SHFT                             16u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_GMU_AO_0_CLOCK_AVAILABLE_1_CYCLE_AFTER_WAKEUP_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_GMU_AO_0_CLOCK_AVAILABLE_2_CYCLE_AFTER_WAKEUP_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_GMU_AO_0_CLOCK_AVAILABLE_3_CYCLE_AFTER_WAKEUP_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_GMU_AO_0_CLOCK_AVAILABLE_4_CYCLE_AFTER_WAKEUP_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_GMU_AO_0_CLOCK_AVAILABLE_5_CYCLE_AFTER_WAKEUP_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_GMU_AO_0_CLOCK_AVAILABLE_6_CYCLE_AFTER_WAKEUP_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_GMU_AO_0_CLOCK_AVAILABLE_7_CYCLE_AFTER_WAKEUP_FVAL        0x6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLLLMDELAY_GMU_AO_0_CLOCK_AVAILABLE_8_CYCLE_AFTER_WAKEUP_FVAL        0x7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_BMSK                          0x700u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_SHFT                              8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_GMU_AO_0_CLOCK_AVAILABLE_1_CYCLE_AFTER_WAKEUP_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_GMU_AO_0_CLOCK_AVAILABLE_2_CYCLE_AFTER_WAKEUP_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_GMU_AO_0_CLOCK_AVAILABLE_3_CYCLE_AFTER_WAKEUP_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_GMU_AO_0_CLOCK_AVAILABLE_4_CYCLE_AFTER_WAKEUP_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_GMU_AO_0_CLOCK_AVAILABLE_5_CYCLE_AFTER_WAKEUP_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_GMU_AO_0_CLOCK_AVAILABLE_6_CYCLE_AFTER_WAKEUP_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_GMU_AO_0_CLOCK_AVAILABLE_7_CYCLE_AFTER_WAKEUP_FVAL        0x6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCSRDELAY_GMU_AO_0_CLOCK_AVAILABLE_8_CYCLE_AFTER_WAKEUP_FVAL        0x7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_BMSK                        0x70u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_SHFT                           4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_GMU_AO_0_CLOCK_AVAILABLE_1_CYCLE_AFTER_WAKEUP_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_GMU_AO_0_CLOCK_AVAILABLE_2_CYCLE_AFTER_WAKEUP_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_GMU_AO_0_CLOCK_AVAILABLE_3_CYCLE_AFTER_WAKEUP_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_GMU_AO_0_CLOCK_AVAILABLE_4_CYCLE_AFTER_WAKEUP_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_GMU_AO_0_CLOCK_AVAILABLE_5_CYCLE_AFTER_WAKEUP_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_GMU_AO_0_CLOCK_AVAILABLE_6_CYCLE_AFTER_WAKEUP_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_GMU_AO_0_CLOCK_AVAILABLE_7_CYCLE_AFTER_WAKEUP_FVAL        0x6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3BUSDELAY_GMU_AO_0_CLOCK_AVAILABLE_8_CYCLE_AFTER_WAKEUP_FVAL        0x7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_BMSK                        0x7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_SHFT                          0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_GMU_AO_0_CLOCK_AVAILABLE_1_CYCLE_AFTER_WAKEUP_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_GMU_AO_0_CLOCK_AVAILABLE_2_CYCLE_AFTER_WAKEUP_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_GMU_AO_0_CLOCK_AVAILABLE_3_CYCLE_AFTER_WAKEUP_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_GMU_AO_0_CLOCK_AVAILABLE_4_CYCLE_AFTER_WAKEUP_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_GMU_AO_0_CLOCK_AVAILABLE_5_CYCLE_AFTER_WAKEUP_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_GMU_AO_0_CLOCK_AVAILABLE_6_CYCLE_AFTER_WAKEUP_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_GMU_AO_0_CLOCK_AVAILABLE_7_CYCLE_AFTER_WAKEUP_FVAL        0x6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_DELAY_CNTL_CGCCNTLCM3COREDELAY_GMU_AO_0_CLOCK_AVAILABLE_8_CYCLE_AFTER_WAKEUP_FVAL        0x7u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_ADDR                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x2cu)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_OFFS                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x2cu)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_RMSK                                          0xffffu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_BMSK                           0xf000u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_SHFT                               12u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_32_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_64_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_96_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_128_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_5_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_6_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_7_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_8_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_9_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_10_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x9u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_11_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xau
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_12_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xbu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_13_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xcu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_14_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xdu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_15_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xeu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLLLMHYST_GMU_AO_0_NEED_16_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xfu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_BMSK                            0xf00u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_SHFT                                8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_32_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_64_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_96_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_128_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_5_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_6_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_7_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_8_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_9_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_10_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x9u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_11_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xau
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_12_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xbu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_13_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xcu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_14_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xdu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_15_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xeu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCSRHYST_GMU_AO_0_NEED_16_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xfu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_BMSK                          0xf0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_SHFT                             4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_32_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_64_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_96_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_128_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_5_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_6_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_7_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_8_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_9_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_10_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x9u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_11_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xau
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_12_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xbu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_13_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xcu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_14_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xdu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_15_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xeu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3BUSHYST_GMU_AO_0_NEED_16_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xfu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_BMSK                          0xfu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_SHFT                            0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_32_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_64_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_96_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_128_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_5_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_6_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_7_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_8_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_9_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_10_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0x9u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_11_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xau
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_12_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xbu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_13_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xcu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_14_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xdu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_15_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xeu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_CGC_HYST_CNTL_CGCCNTLCM3COREHYST_GMU_AO_0_NEED_16_CYCLES_DELAY_TO_TURN_OFF_CLK_ALIVE_FROM_BUSY_MONITOR_FVAL        0xfu

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_ADDR                                     (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x30u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_OFFS                                     (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x30u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_RMSK                                     0x7ffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXGXCPUBUSYIGNAHB_BMSK                   0x40000000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXGXCPUBUSYIGNAHB_SHFT                           30u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXHUBHOSTBUSY_BMSK                       0x20000000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXHUBHOSTBUSY_SHFT                               29u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXHUBNONHOSTBUSY_BMSK                    0x10000000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXHUBNONHOSTBUSY_SHFT                            28u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXDBGCTRLBUSY_BMSK                        0x8000000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXDBGCTRLBUSY_SHFT                               27u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXVBIFBUSY_BMSK                           0x4000000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CXVBIFBUSY_SHFT                                  26u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_SMMUBUSY_BMSK                             0x2000000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_SMMUBUSY_SHFT                                    25u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_GMUBUSY_BMSK                              0x1000000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_GMUBUSY_SHFT                                     24u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_GPUBUSYIGNAHB_BMSK                         0x800000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_GPUBUSYIGNAHB_SHFT                               23u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_GPUBUSYIGNAHBCP_BMSK                       0x400000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_GPUBUSYIGNAHBCP_SHFT                             22u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_HLSQBUSY_BMSK                              0x200000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_HLSQBUSY_SHFT                                    21u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_VSCBUSY_BMSK                               0x100000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_VSCBUSY_SHFT                                     20u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_TPL1BUSY_BMSK                               0x80000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_TPL1BUSY_SHFT                                    19u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_SPBUSY_BMSK                                 0x40000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_SPBUSY_SHFT                                      18u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_UCHEBUSY_BMSK                               0x20000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_UCHEBUSY_SHFT                                    17u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_VPCBUSY_BMSK                                0x10000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_VPCBUSY_SHFT                                     16u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_VFDBUSY_BMSK                                 0x8000u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_VFDBUSY_SHFT                                     15u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_TESSBUSY_BMSK                                0x4000u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_TESSBUSY_SHFT                                    14u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_PCVSDBUSY_BMSK                               0x2000u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_PCVSDBUSY_SHFT                                   13u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_PCDCALLBUSY_BMSK                             0x1000u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_PCDCALLBUSY_SHFT                                 12u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_COMDCOMBUSY_BMSK                              0x800u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_COMDCOMBUSY_SHFT                                 11u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_LRZBUSY_BMSK                                  0x400u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_LRZBUSY_SHFT                                     10u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_A2DBUSY_BMSK                                  0x200u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_A2DBUSY_SHFT                                      9u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CCUBUSY_BMSK                                  0x100u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CCUBUSY_SHFT                                      8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_RBBUSY_BMSK                                    0x80u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_RBBUSY_SHFT                                       7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_RASBUSY_BMSK                                   0x40u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_RASBUSY_SHFT                                      6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_TSEBUSY_BMSK                                   0x20u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_TSEBUSY_SHFT                                      5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_VBIFGXFPARTBUSY_BMSK                           0x10u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_VBIFGXFPARTBUSY_SHFT                              4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_GFXDBGCBUSY_BMSK                                0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_GFXDBGCBUSY_SHFT                                  3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CPBUSY_BMSK                                     0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CPBUSY_SHFT                                       2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CPAHBBUSYCPMASTER_BMSK                          0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CPAHBBUSYCPMASTER_SHFT                            1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CPAHBBUSYCXMASTER_BMSK                          0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS_CPAHBBUSYCXMASTER_SHFT                            0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_ADDR                                    (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x34u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_OFFS                                    (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x34u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_RMSK                                         0xfffu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_VBIFCXPORTBUSY_BMSK                          0x800u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_VBIFCXPORTBUSY_SHFT                             11u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_VBIFCOREBUSY_BMSK                            0x400u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_VBIFCOREBUSY_SHFT                               10u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_SMMUBUSY_BMSK                                0x200u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_SMMUBUSY_SHFT                                    9u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_GMUAOBUSY_BMSK                               0x100u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_GMUAOBUSY_SHFT                                   8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_GMUCXBUSY_BMSK                                0x80u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_GMUCXBUSY_SHFT                                   7u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBSMMUSLAVEBUSY_BMSK                      0x40u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBSMMUSLAVEBUSY_SHFT                         6u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBCPSLAVEBUSY_BMSK                        0x20u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBCPSLAVEBUSY_SHFT                           5u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBGMUAOSLAVEBUSY_BMSK                     0x10u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBGMUAOSLAVEBUSY_SHFT                        4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBGMUCXSLAVEBUSY_BMSK                      0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBGMUCXSLAVEBUSY_SHFT                        3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBCPMASTERBUSY_BMSK                        0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBCPMASTERBUSY_SHFT                          2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBHOSTMASTERBUSY_BMSK                      0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBHOSTMASTERBUSY_SHFT                        1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBGMUCXMASTERBUSY_BMSK                     0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_STATUS2_AHBHUBGMUCXMASTERBUSY_SHFT                       0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_ADDR                                       (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x38u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_OFFS                                       (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x38u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_RMSK                                       0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_GPUCXBUSYSTATUSMASK_BMSK                   0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GPU_CX_BUSY_MASK_GPUCXBUSYSTATUSMASK_SHFT                            0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_ADDR                                         (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x40u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_OFFS                                         (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x40u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_RMSK                                                0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_AHBFENCEMODE_BMSK                                   0x3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_AHBFENCEMODE_SHFT                                     0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_AHBFENCEMODE_GMU_AO_0_GMU_FENCE_ALLOW_FVAL          0x0u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_AHBFENCEMODE_GMU_AO_0_GMU_FENCE_BLOCK_FVAL          0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_CTRL_AHBFENCEMODE_GMU_AO_0_GMU_FENCE_DROP_FVAL           0x2u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_ADDR                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x44u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_OFFS                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x44u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_RMSK                                      0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_FENCERANGEENABLE_BMSK                     0x80000000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_FENCERANGEENABLE_SHFT                             31u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_FENCESPAN_BMSK                            0x7ffc0000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_FENCESPAN_SHFT                                    18u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_FENCEBASEADDR_BMSK                           0x3fffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_0_FENCEBASEADDR_SHFT                                 0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_ADDR                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x48u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_OFFS                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x48u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_RMSK                                      0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_FENCERANGEENABLE_BMSK                     0x80000000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_FENCERANGEENABLE_SHFT                             31u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_FENCESPAN_BMSK                            0x7ffc0000ul
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_FENCESPAN_SHFT                                    18u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_FENCEBASEADDR_BMSK                           0x3fffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_RANGE_1_FENCEBASEADDR_SHFT                                 0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_ADDR                                       (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x4cu)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_OFFS                                       (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x4cu)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_RMSK                                           0xff1fu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPCOUNTER_BMSK                          0xff00u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPCOUNTER_SHFT                               8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_AHBFENCEACK_BMSK                                 0x10u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_AHBFENCEACK_SHFT                                    4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPPED3_BMSK                                0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPPED3_SHFT                                  3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPPED2_BMSK                                0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPPED2_SHFT                                  2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPPED1_BMSK                                0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPPED1_SHFT                                  1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPPED0_BMSK                                0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_WRITEDROPPED0_SHFT                                  0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_ADDR                                   (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x50u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_OFFS                                   (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x50u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_RMSK                                         0x1fu
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_AHBFENCEACK_BMSK                             0x10u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_AHBFENCEACK_SHFT                                4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_WRITEDROPPED3_BMSK                            0x8u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_WRITEDROPPED3_SHFT                              3u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_WRITEDROPPED2_BMSK                            0x4u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_WRITEDROPPED2_SHFT                              2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_WRITEDROPPED1_BMSK                            0x2u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_WRITEDROPPED1_SHFT                              1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_WRITEDROPPED0_BMSK                            0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_AHB_FENCE_STATUS_CLR_WRITEDROPPED0_SHFT                              0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_RBBM_INT_UNMASKED_STATUS_SHADOW_ADDR                        (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x54u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_RBBM_INT_UNMASKED_STATUS_SHADOW_OFFS                        (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x54u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_RBBM_INT_UNMASKED_STATUS_SHADOW_RMSK                        0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_RBBM_INT_UNMASKED_STATUS_SHADOW_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_RBBM_INT_UNMASKED_STATUS_SHADOW_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_RBBM_INT_UNMASKED_STATUS_SHADOW_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_RBBM_INT_UNMASKED_STATUS_SHADOW_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_RBBM_INT_UNMASKED_STATUS_SHADOW_RBBMINTSTATUS_BMSK          0xfffffffful
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_RBBM_INT_UNMASKED_STATUS_SHADOW_RBBMINTSTATUS_SHFT                   0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_ADDR                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0x58u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_OFFS                                      (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0x58u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_RMSK                                             0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_GPUBANDGAPEN_BMSK                                0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_GMU_AO_SPARE_CNTL_GPUBANDGAPEN_SHFT                                  0u

#define HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_ADDR                                            (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE      + 0xa0u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_OFFS                                            (SAIL_TO_MD_GPU_GMU_AO_BLK_DEC0_REG_BASE_OFFS + 0xa0u)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_RMSK                                                   0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_IN                    \
                in_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_ADDR)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_INM(m)            \
                in_dword_masked(HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_ADDR, m)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_OUT(v)            \
                out_dword(HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_ADDR,v)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_OUTM(m,v) \
                out_dword_masked_ns(HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_ADDR,m,v,HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_IN)
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_CLRCBRXFSM_BMSK                                        0x1u
#define HWIO_SAIL_TO_MD_GPU_GMU_AO_CLR_CBRXFSM_CLRCBRXFSM_SHFT                                          0u


#endif /* __G_SAIL_TO_MD_GPU_GMU_AO_HWIO_H__ */
