#include "HALxpu3Internal.h"
#include "HALhwio.h"
#include "HALSOCHWIOTarget.h"
#include "HALxpu3Hwio.h"
#include "HALhwioXpu3Generic.h"
#include "HALxpu3HWIOTarget.h"

#undef XPU_ADDR_TYPE
#define XPU_ADDR_TYPE(x) 0x1

#if !defined(XPU_IMAGE_SIZE_REDUCTION)
HAL_xpu3_Xpu3BaseAddressInfoType g_xpu_base_addr_array[]=
{
	{HAL_XPU2_CRYPTO0_BAM, XPU_ADDR_TYPE(CRYPTO0_CRYPTO_BAM_XPU3_GCR0), "CRYPTO0_BAM"},
	{HAL_XPU2_DCC, XPU_ADDR_TYPE(DCC_XPU3_GCR0), "DCC"},
	{HAL_XPU2_IPA_0_GSI_TOP, XPU_ADDR_TYPE(IPA_0_GSI_TOP_XPU3_GCR0), "IPA_0_GSI_TOP"},
	{HAL_XPU2_MMSS, XPU_ADDR_TYPE(MDSS_XPU_XPU3_GCR0), "MMSS"},
	{HAL_XPU2_BAM_BLSP1_DMA, XPU_ADDR_TYPE(QUPV3_0_XPU3_GCR0),"BAM_BLSP1_DMA"},
	{HAL_XPU2_BAM_BLSP2_DMA, XPU_ADDR_TYPE(QUPV3_1_XPU3_GCR0), "BAM_BLSP2_DMA"},
	{HAL_XPU2_SP_SCSR, XPU_ADDR_TYPE(SP_CNOC_SP_SCSR_XPU3_GCR0), "SP_SCSR"},
	{HAL_XPU2_SSC_BLSP_BAM, XPU_ADDR_TYPE(SSC_QUPV3_XPU3_GCR0), "SSC_BLSP_BAM"},
	{HAL_XPU2_TLMM_XPU_NORTH, XPU_ADDR_TYPE(TLMM_XPU_NORTH_XPU3_GCR0), "TLMM_XPU_NORTH"},
	{HAL_XPU2_UFS_ICE, XPU_ADDR_TYPE(UFS_MEM_ICE_XPU3_GCR0), "UFS_ICE"},
	{HAL_XPU2_GCC_RPU, XPU_ADDR_TYPE(GCC_RPU_XPU3_GCR0), "GCC_RPU"},
	{HAL_XPU2_TCSR_MUTEX, XPU_ADDR_TYPE(TCSR_MUTEX_XPU3_GCR0), "TCSR_MUTEX"},
	{HAL_XPU2_TCSR_REGS, XPU_ADDR_TYPE(TCSR_REGS_XPU3_GCR0), "TCSR_REGS"},
	{HAL_XPU2_IMEM_APU, XPU_ADDR_TYPE(OCIMEM_APU_XPU3_GCR0), "IMEM_APU"},
	{HAL_XPU2_RAMBLUR_PIMEM_APU, XPU_ADDR_TYPE(RAMBLUR_PIMEM_APU_XPU3_GCR0), "RAMBLUR_PIMEM_APU"},
	{HAL_XPU2_SEC_CTRL_APU, XPU_ADDR_TYPE(SEC_CTRL_APU_XPU3_GCR0), "SEC_CTRL_APU"},
	{HAL_XPU2_ANOC1_MPU, XPU_ADDR_TYPE(A1_NOC_MS_MPU_CFG_XPU3_GCR0),"ANOC1_MPU"},
	{HAL_XPU2_ANOC2_MPU, XPU_ADDR_TYPE(A2_NOC_MS_MPU_CFG_XPU3_GCR0), "ANOC2_MPU"},
	{HAL_XPU2_BOOT_ROM, XPU_ADDR_TYPE(BOOT_ROM_XPU3_GCR0),"BOOT_ROM"},
	{HAL_XPU2_CNOC_SNOC_MS_MPU, XPU_ADDR_TYPE(CNOC_SNOC_MPU_XPU3_GCR0), "CNOC_SNOC_MS_MPU"},
	{HAL_XPU2_CNOC_SNOC_MPU, XPU_ADDR_TYPE(CNOC_SS_MPU_XPU3_GCR0), "CNOC_SNOC_MPU"},
	{HAL_XPU2_IMEM_MPU, XPU_ADDR_TYPE(OCIMEM_MPU_XPU3_GCR0), "IMEM_MPU"},
	{HAL_XPU2_PMIC_ARB, XPU_ADDR_TYPE(PMIC_ARB_XPU3_GCR0), "PMIC_ARB"},
	{HAL_XPU2_QM_MPU_CFG, XPU_ADDR_TYPE(QM_MPU_CFG_QM_MPU_CFG_XPU3_GCR0), "QM_MPU_CFG"},
	{HAL_XPU2_RAMBLUR_PIMEM_MPU, XPU_ADDR_TYPE(RAMBLUR_PIMEM_MPU_XPU3_GCR0), "RAMBLUR_PIMEM_MPU"},
	{HAL_XPU2_CFG_SSC, XPU_ADDR_TYPE(SSC_MPU_CFG_SSC_MPU_CFG_XPU3_GCR0), "CFG_SSC"},
	{HAL_XPU2_SSC_Q6_MPU, XPU_ADDR_TYPE(SSC_Q6_MPU_XPU3_GCR0), "SSC_Q6_MPU"},
	{HAL_XPU2_BIMC_MPU0, XPU_ADDR_TYPE(LLCC0_LLCC_XPU3_GCR0), "BIMC_MPU0"},
	{HAL_XPU2_BIMC_MPU1, XPU_ADDR_TYPE(LLCC1_LLCC_XPU3_GCR0), "BIMC_MPU1"},
	{HAL_XPU2_SDC1_SDCC_ICE, XPU_ADDR_TYPE(UFS_CARD_ICE_XPU3_GCR0), "SDC1_SDCC_ICE"},
	{HAL_XPU2_TLMM_XPU_SOUTH, XPU_ADDR_TYPE(TLMM_XPU_SOUTH_XPU3_GCR0), "TLMM_XPU_SOUTH"},
	{HAL_XPU2_TITAN_SS_APU, XPU_ADDR_TYPE(TITAN_A_XPU3_XPU3_GCR0), "TITAN_SS_APU"},
	{HAL_MEMNOC_MS_MPU, XPU_ADDR_TYPE(MEMNOC_XPU3_GCR0), "MEMNOC_MS_MPU"},
	{HAL_XPU2_CNOC_AOSS_MPU, XPU_ADDR_TYPE(CNOC_AOSS_MPU_XPU3_GCR0), "CNOC_AOSS_MPU"},
	{HAL_XPU2_LLCC_BROADCAST_MPU, XPU_ADDR_TYPE(LLCC_BROADCAST_LLCC_XPU3_GCR0), "LLCC_BROADCAST_MPU"},
	{HAL_XPU2_SSC_SDC_MPU, XPU_ADDR_TYPE(SSC_SDC_MPU_XPU3_GCR0), "SSC_SDC_MPU"},
	{HAL_XPU2_BIMC_MPU2, XPU_ADDR_TYPE(LLCC2_LLCC_XPU3_GCR0), "BIMC_MPU2"},
	{HAL_XPU2_MSS_NAV_MPU, XPU_ADDR_TYPE(MSS_NAV_MS_MPU_CFG_XPU3_GCR0), "MSS_NAV_MPU"},
	{HAL_DC_NOC_BROADCAST_MPU, XPU_ADDR_TYPE(DC_NOC_BROADCAST_MPU_XPU3_GCR0), "DC_NOC_BROADCAST_MPU"},
	{HAL_AOSS_MPU, XPU_ADDR_TYPE(AOSS_MPU_XPU3_GCR0), "AOSS_MPU"},
	{HAL_XPU2_BIMC_MPU3, XPU_ADDR_TYPE(LLCC3_LLCC_XPU3_GCR0), "BIMC_MPU3"},
	{HAL_DC_NOC_NON_BROADCAST_MPU, XPU_ADDR_TYPE(DC_NOC_NON_BROADCAST_MPU_XPU3_GCR0), "DC_NOC_NON_BROADCAST_MPU"},
	{HAL_XPU2_SPDM_APU, XPU_ADDR_TYPE(SPDM_XPU3_GCR0), "SPDM_APU"},
	{HAL_XPU2_TLMM_XPU_EAST, XPU_ADDR_TYPE(TLMM_XPU_EAST_XPU3_GCR0), "TLMM_XPU_EAST"},
};
#else
HAL_xpu3_Xpu3BaseAddressInfoType g_xpu_base_addr_array[]=
{
	{HAL_XPU2_CRYPTO0_BAM, XPU_ADDR_TYPE(CRYPTO0_CRYPTO_BAM_XPU3_GCR0)},
	{HAL_XPU2_DCC, XPU_ADDR_TYPE(DCC_XPU3_GCR0)},
	{HAL_XPU2_IPA_0_GSI_TOP, XPU_ADDR_TYPE(IPA_0_GSI_TOP_XPU3_GCR0)},
	{HAL_XPU2_MMSS, XPU_ADDR_TYPE(MDSS_XPU_XPU3_GCR0)},
	{HAL_XPU2_BAM_BLSP1_DMA, XPU_ADDR_TYPE(QUPV3_0_XPU3_GCR0)},
	{HAL_XPU2_BAM_BLSP2_DMA, XPU_ADDR_TYPE(QUPV3_1_XPU3_GCR0)},
	{HAL_XPU2_SP_SCSR, XPU_ADDR_TYPE(SP_CNOC_SP_SCSR_XPU3_GCR0)},
	{HAL_XPU2_SSC_BLSP_BAM, XPU_ADDR_TYPE(SSC_QUPV3_XPU3_GCR0)},
	{HAL_XPU2_TLMM_XPU_NORTH, XPU_ADDR_TYPE(TLMM_XPU_NORTH_XPU3_GCR0)},
	{HAL_XPU2_UFS_ICE, XPU_ADDR_TYPE(UFS_MEM_ICE_XPU3_GCR0)},
	{HAL_XPU2_GCC_RPU, XPU_ADDR_TYPE(GCC_RPU_XPU3_GCR0)},
	{HAL_XPU2_TCSR_MUTEX, XPU_ADDR_TYPE(TCSR_MUTEX_XPU3_GCR0)},
	{HAL_XPU2_TCSR_REGS, XPU_ADDR_TYPE(TCSR_REGS_XPU3_GCR0)},
	{HAL_XPU2_IMEM_APU, XPU_ADDR_TYPE(OCIMEM_APU_XPU3_GCR0)},
	{HAL_XPU2_RAMBLUR_PIMEM_APU, XPU_ADDR_TYPE(RAMBLUR_PIMEM_APU_XPU3_GCR0)},
	{HAL_XPU2_SEC_CTRL_APU, XPU_ADDR_TYPE(SEC_CTRL_APU_XPU3_GCR0)},
	{HAL_XPU2_ANOC1_MPU, XPU_ADDR_TYPE(A1_NOC_MS_MPU_CFG_XPU3_GCR0)},
	{HAL_XPU2_ANOC2_MPU, XPU_ADDR_TYPE(A2_NOC_MS_MPU_CFG_XPU3_GCR0)},
	{HAL_XPU2_BOOT_ROM, XPU_ADDR_TYPE(BOOT_ROM_XPU3_GCR0)},
	{HAL_XPU2_CNOC_SNOC_MS_MPU, XPU_ADDR_TYPE(CNOC_SNOC_MPU_XPU3_GCR0)},
	{HAL_XPU2_CNOC_SNOC_MPU, XPU_ADDR_TYPE(CNOC_SS_MPU_XPU3_GCR0)},
	{HAL_XPU2_IMEM_MPU, XPU_ADDR_TYPE(OCIMEM_MPU_XPU3_GCR0)},
	{HAL_XPU2_PMIC_ARB, XPU_ADDR_TYPE(PMIC_ARB_XPU3_GCR0)},
	{HAL_XPU2_QM_MPU_CFG, XPU_ADDR_TYPE(QM_MPU_CFG_QM_MPU_CFG_XPU3_GCR0)},
	{HAL_XPU2_RAMBLUR_PIMEM_MPU, XPU_ADDR_TYPE(RAMBLUR_PIMEM_MPU_XPU3_GCR0)},
	{HAL_XPU2_CFG_SSC, XPU_ADDR_TYPE(SSC_MPU_CFG_SSC_MPU_CFG_XPU3_GCR0)},
	{HAL_XPU2_SSC_Q6_MPU, XPU_ADDR_TYPE(SSC_Q6_MPU_XPU3_GCR0)},
	{HAL_XPU2_BIMC_MPU0, XPU_ADDR_TYPE(LLCC0_LLCC_XPU3_GCR0)},
	{HAL_XPU2_BIMC_MPU1, XPU_ADDR_TYPE(LLCC1_LLCC_XPU3_GCR0)},
	{HAL_XPU2_SDC1_SDCC_ICE, XPU_ADDR_TYPE(UFS_CARD_ICE_XPU3_GCR0)},
	{HAL_XPU2_TLMM_XPU_SOUTH, XPU_ADDR_TYPE(TLMM_XPU_SOUTH_XPU3_GCR0)},
	{HAL_XPU2_TITAN_SS_APU, XPU_ADDR_TYPE(TITAN_A_XPU3_XPU3_GCR0)},
	{HAL_MEMNOC_MS_MPU, XPU_ADDR_TYPE(MEMNOC_XPU3_GCR0)},
	{HAL_XPU2_CNOC_AOSS_MPU, XPU_ADDR_TYPE(CNOC_AOSS_MPU_XPU3_GCR0)},
	{HAL_XPU2_LLCC_BROADCAST_MPU, XPU_ADDR_TYPE(LLCC_BROADCAST_LLCC_XPU3_GCR0)},
	{HAL_XPU2_SSC_SDC_MPU, XPU_ADDR_TYPE(SSC_SDC_MPU_XPU3_GCR0)},
	{HAL_XPU2_BIMC_MPU2, XPU_ADDR_TYPE(LLCC2_LLCC_XPU3_GCR0)},
	{HAL_XPU2_MSS_NAV_MPU, XPU_ADDR_TYPE(MSS_NAV_MS_MPU_CFG_XPU3_GCR0)},
	{HAL_DC_NOC_BROADCAST_MPU, XPU_ADDR_TYPE(DC_NOC_BROADCAST_MPU_XPU3_GCR0)},
	{HAL_AOSS_MPU, XPU_ADDR_TYPE(AOSS_MPU_XPU3_GCR0)},
	{HAL_XPU2_BIMC_MPU3, XPU_ADDR_TYPE(LLCC3_LLCC_XPU3_GCR0)},
	{HAL_DC_NOC_NON_BROADCAST_MPU, XPU_ADDR_TYPE(DC_NOC_NON_BROADCAST_MPU_XPU3_GCR0)},
	{HAL_XPU2_SPDM_APU, XPU_ADDR_TYPE(SPDM_XPU3_GCR0)},
	{HAL_XPU2_TLMM_XPU_EAST, XPU_ADDR_TYPE(TLMM_XPU_EAST_XPU3_GCR0)},
};
#endif

uint32 g_xpu_base_addr_array_count = sizeof(g_xpu_base_addr_array)/sizeof(g_xpu_base_addr_array[0]);

